In [1]:
import numpy as np

In [44]:
def vyravnivanie(s1, s2):
    len_s1 = len(s1)+1
    len_s2 = len(s2)+1
    d = np.zeros( (len_s1, len_s2)) 
    d[0][0] = 0
    for i_a in range(1,len_s1):
        d[i_a][0]=i_a
    for i_b in range(1,len_s2):
        d[0][i_b]=i_b
    for i_a in range(1,len_s1):
        for i_b in range(1,len_s2):    
            d[i_a][i_b]=min(d[i_a-1][i_b]+1, d[i_a][i_b-1]+1, d[i_a-1][i_b-1]+ (1 if s1[i_a-1]!=s2[i_b-1]else 0) )
    print(d)
    print("Wage is {}".format(d[len_s1-1][len_s2-1]))
    len_s1=len_s1-1
    len_s2=len_s2-1
    
    res1=""
    res2=""
    while len_s1!=0 or len_s2!=0:
        if (d[len_s1-1][len_s2-1]<=min(d[len_s1-1][len_s2],d[len_s1][len_s2-1])):
            res1=s1[len_s1-1]+res1
            res2=s2[len_s2-1]+res2
            len_s1=len_s1-1
            len_s2=len_s2-1
        elif (d[len_s1-1][len_s2] <=min(d[len_s1-1][len_s2-1],d[len_s1][len_s2-1])):
            res1=s1[len_s1-1]+res1
            res2="-"+res2
            len_s1=len_s1-1
        else:
            res1="-"+res1
            res2=s2[len_s2-1]+res2
            len_s2=len_s2-1
    print(res1+"\n"+res2)
    

In [45]:
vyravnivanie(s1 = "CCAAGGCT",s2 = "CCAGAGAC")

[[0. 1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 0. 1. 2. 3. 4. 5. 6. 7.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [4. 3. 2. 1. 1. 1. 2. 3. 4.]
 [5. 4. 3. 2. 1. 2. 1. 2. 3.]
 [6. 5. 4. 3. 2. 2. 2. 2. 3.]
 [7. 6. 5. 4. 3. 3. 3. 3. 2.]
 [8. 7. 6. 5. 4. 4. 4. 4. 3.]]
Wage is 3.0
CCA-AGGCT
CCAGAGAC-


In [46]:
vyravnivanie(s1 = "CCAAGGCT",s2 = "CCAAGGCT")

[[0. 1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 0. 1. 2. 3. 4. 5. 6. 7.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [7. 6. 5. 4. 3. 2. 1. 0. 1.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0.]]
Wage is 0.0
CCAAGGCT
CCAAGGCT


In [47]:
vyravnivanie(s1 = "CCAAGTTT",s2 = "CCAAGGCC")

[[0. 1. 2. 3. 4. 5. 6. 7. 8.]
 [1. 0. 1. 2. 3. 4. 5. 6. 7.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [6. 5. 4. 3. 2. 1. 1. 2. 3.]
 [7. 6. 5. 4. 3. 2. 2. 2. 3.]
 [8. 7. 6. 5. 4. 3. 3. 3. 3.]]
Wage is 3.0
CCAAGTTT
CCAAGGCC
